interface Industry {
  slug: string;
  title: string;
}

export const industries: Industry[] = [
  { slug: 'small-businesses', title: 'Small Businesses' },
  { slug: 'startups', title: 'Startups' },
  { slug: 'lawyers', title: 'Lawyers' },
  { slug: 'plumbers', title: 'Plumbers' },
  { slug: 'electricians', title: 'Electricians' },
  { slug: 'hvac', title: 'HVAC' },
  { slug: 'dentists', title: 'Dentists' },
  { slug: 'real-estate-agents', title: 'Real Estate Agents' },
  { slug: 'restaurants', title: 'Restaurants' },
  { slug: 'retail-stores', title: 'Retail Stores' },
  { slug: 'auto-repair', title: 'Auto Repair' },
  { slug: 'accountants', title: 'Accountants' },
  { slug: 'medical-practices', title: 'Medical Practices' },
  { slug: 'tech-companies', title: 'Tech Companies' },
  { slug: 'fitness-centers', title: 'Fitness Centers' },
  { slug: 'salons', title: 'Salons' },
  { slug: 'marketing-agencies', title: 'Marketing Agencies' },
  { slug: 'consulting-firms', title: 'Consulting Firms' },
  { slug: 'construction-companies', title: 'Construction Companies' },
  { slug: 'insurance-agencies', title: 'Insurance Agencies' },
  { slug: 'travel-agencies', title: 'Travel Agencies' },
  { slug: 'non-profits', title: 'Non-Profits' },
  { slug: 'educational-institutions', title: 'Educational Institutions' },
  { slug: 'legal-services', title: 'Legal Services' },
  { slug: 'healthcare-providers', title: 'Healthcare Providers' },
  { slug: 'graphic-designers', title: 'Graphic Designers' },
  { slug: 'photographers', title: 'Photographers' },
  { slug: 'event-planners', title: 'Event Planners' },
  { slug: 'software-developers', title: 'Software Developers' },
  { slug: 'e-commerce', title: 'E-commerce' },
  { slug: 'financial-services', title: 'Financial Services' },
  { slug: 'human-resources', title: 'Human Resources' },
  { slug: 'manufacturing', title: 'Manufacturing' },
  { slug: 'logistics', title: 'Logistics' },
  { slug: 'pharmaceuticals', title: 'Pharmaceuticals' },
  { slug: 'energy', title: 'Energy' },
  { slug: 'telecommunications', title: 'Telecommunications' },
  { slug: 'media', title: 'Media' },
  { slug: 'transportation', title: 'Transportation' },
  { slug: 'hospitality', title: 'Hospitality' },
  { slug: 'automotive', title: 'Automotive' },
  { slug: 'biotechnology', title: 'Biotechnology' },
  { slug: 'aerospace', title: 'Aerospace' },
  { slug: 'food-and-beverage', title: 'Food and Beverage' },
  { slug: 'fashion', title: 'Fashion' },
  { slug: 'agriculture', title: 'Agriculture' },
  { slug: 'restaurants', title: 'Restaurants' },
];

